### ISSUE TITLE
Minion Prefix Questions

### ISSUE THREAD

**Issue by ninjada** [JensRantil/saltstack-autoscaling#4]
Hello, first off saw this referenced on the salt-users group and it looks great so thanks for sharing!

Just wondering regarding the PLACEHOLDER_MINION_PREFIX, will it be possible to have multiple prefixes?

For example, say I have multiple autoscale groups and I need an individual prefix for each of them in the format "(autoscale-group-name)-(instance-id)", is that workable?

**Comment by JensRantil** [comment]
Hi @ninjada, I'm glad you liked this initiative!

This repository specifically only supports a single autoscaling group (for simplicity!). However, by having different [user data](https://github.com/JensRantil/saltstack-autoscaling/blob/master/cloud-init.auto-scaling.example) for each Launch Configurations, you can have different prefixes for different auto scaling groups.

When different autoscaling groups have different prefixes, you can easily duplicate [this](https://github.com/JensRantil/saltstack-autoscaling/blob/master/reactors/autoscaling/minion-connected.sls) and [this](https://github.com/JensRantil/saltstack-autoscaling/blob/master/reactors/autoscaling/sqs-event.sls) file and change their hardcoded prefixes to the second prefix. Don't forget to also add the duplicated files to [master configuration](https://github.com/JensRantil/saltstack-autoscaling/blob/master/master-conf/reactors.conf).

All my autoscaling groups are using the same SNS topic.

Let me know if I didn't make myself clear enough.
